---
author: "wiesehahn"
date: "2021-04-13"
output: html_document
---


## Unterschiede

Sowohl die Waldmaskierung basierend auf dem Basis-DLM als auch die Waldmaske der Copernicus High Resolution Layers und die eigene basierend auf Random Forest und OpenStreetMap ergeben gute Gesamtgenauigkeiten. Die Unterschiede liegen zum einen bei der Abgrenzung von Wald und Nichtwald im Stadt und Agrarbereich, wo primär fernerkundungsbasierte Masken Gehölz kartieren (Landbedeckung) während diese Gebiete im Basis-DLM basierend auf der Landnutzung herausfallen. Ein ähnlicher Unterschied ergibt sich auf Kahlflächen, Waldblößen etc. wo temporär kein Baumbestand vorhanden ist, die Landnutzung aber weiterhin Wald ist. 


### Basis-DLM
- es fehlen vor allem kleinere Baumbestände in Stadtnähe oder der Agrarlandschaft (durch Maskierung mit Corine Land Cover)
- Kahlflächen werden als Wald ausgewiesen
- Generell wird Waldfläche unterschätzt

### Copernicus HRL Forest
- Gehölz wird gut erkannt
- dadurch in urbanen und Agrargebieten zu viele Pixel als Wald ausgewiesen
- Kahlflächen werden als Nichtwald ausgewiesen
- Generell wird Waldfläche überschätzt (Nutzergenauigkeit 0.80)

### RandomForest - OSM
- ähnlich dem HRL, Gehölz wird gut erkannt aber in urbanen und Agrargebieten zu viele Waldpixel
- Kahlflächen werden als Nichtwald ausgewiesen
- Generell wird Waldfläche überschätzt (Nutzergenauigkeit 0.81)

### Mundialis Incora
- Felder etc werden oftmals falsch asl Wald klassifiziert
- Waldfläche wird deutlich überschätzt (Nutzergenauigkeit  0.64)

### Hansen Tree Cover
- geringe Auflösung (30m), dadurch viele Mischpixel
- vor allem in urbanen Bereichen fehlerhaft 

