
## Walddefinitionen

Es gibt keine allgemeingültige Definition für "Wald". Was als solcher angesehen wird, variiert, von Land zu Land und Anwendungsfall zu Anwendungsfall. Häufig wird auch zwischen einer Waldmaske und einer Gehölzmaske unterschieden. Die Gehölzmaske beinhaltet in dem Fall aktuell bestockte Holzbodenflächen, während die Waldmaske auch nicht bestockte Flächen wie beispielsweise Waldwege oder Kahlflächen umfasst. Eine einheitliche Definition dafür gibt es aber auch hier nicht.

Beispielhaft werden hier zwei häufig verwendete Walddefinitionen gegeben, die der Bundeswaldinventur und die der Ernährungs- und Landwirtschaftsorganisation der Vereinten Nationen.

### Walddefinition der Bundeswaldinventur (BWI)

Wald im Sinne der BWI ist, unabhängig von den Angaben im Kataster oder ähnlichen Verzeichnissen, jede mit Forstpflanzen bestockte Grundfläche. Als Wald gelten auch kahl geschlagene oder verlichtete Grundflächen, Waldwege, Waldeinteilungs- und Sicherungsstreifen, Waldblößen und Lichtungen, Waldwiesen, Wildäsungsplätze, Holzlagerplätze, im Wald gelegene Leitungsschneisen, weitere mit dem Wald verbundene und ihm dienende Flächen einschließlich Flächen mit Erholungseinrichtungen, zugewachsene Heiden und Moore, zugewachsene ehemalige Weiden, Almflächen und Hutungen sowie Latschen- und Grünerlenflächen. Heiden, Moore, Weiden, Almflächen und Hutungen gelten als zugewachsen, wenn die natürlich aufgekommene Bestockung ein durchschnittliches Alter von fünf Jahren erreicht hat und wenn mindestens 50 % der Fläche bestockt sind. 

In der Flur oder im bebauten Gebiet gelegene bestockte Flächen unter 1.000 m², Gehölzstreifen unter 10 m Breite und Weihnachtsbaum- und Schmuckreisigkulturen, gewerbliche Forstbaumschulen sowie zum Wohnbereich gehörende Parkanlagen sind nicht Wald im Sinne der BWI. Wasserläufe bis 5 m Breite unterbrechen nicht den Zusammenhang einer Waldfläche. 

Weihnachtsbaum- und Schmuckreisigkulturen sowie Kurzumtriebsplantagen im Wald sind Wald im Sinne der BWI.

### Internationale Walddefinition (FAO)

Wald ist jede Landfläche größer als 0,5 Hektar mit Bäumen höher als 5 m und einer Baumkronenüberschirmung über 10 %, oder Bäume die diese Mindesthöhe erreichen können. Junge Bestände, welche noch unter 5 m Höhe haben und/oder noch keine Baumkronenüberschirmung von mehr als 10 % besitzen, gehören somit auch zum Wald. Ebenso gehören vorübergehend unbestockte Flächen (durch Forstnutzung oder natürliche Störung) zum Wald.

Erläuterungen: 

Beinhaltet Forststraßen, Brandschneisen und andere Freiflächen, Wald in Nationalparks, Naturschutzgebieten und anderen Schutzgebieten, die von besonderem ökologischem, wissenschaftlichem, historischem, kulturellem oder spirituellem Interesse sind.

Beinhaltet Windschutzstreifen, Schutzgürtel und Korridore von Bäumen mit einer Fläche von mehr als 0,5 ha und einer Breite von mehr als 20 Metern.


## National verfügbare Waldmasken

[Copernicus High Resolution Layers (HRL)](https://land.copernicus.eu/pan-european/high-resolution-layers)

-   für 2012, 2015, 2018, (2021) (alle 3 Jahre)
-   Europaweit
-   aus Sentinel-1, Sentinel-2 (sowie Landsat-8 und VHR)
-   2012 und 2015 mit 20m Auflösung (100m für Change Products)
-   2018 mit 10m Auflösung generiert über DIAS (Mundi Web Services) (online seit 2020)
-   Definition für Tree Cover Mask vorhanden
-   Produkte: Tree Cover Density, Forest Type, Forest Additional Support Layer, Dominant Leaf Type, Tree Cover Density Change, Dominante Leaf Type Change
-   nur Forest Type stellt eine Waldmaske dar, alle anderen Layer eine Gehölz- / Baummaske
-   Detailiertes Manual [hier](https://land.copernicus.eu/user-corner/technical-library/forest-2018-user-manual.pdf)

Layer:

-   Tree Cover Density (TCD)

    -   aus HR Bildern mit VHR Bildern und Orthophotos als Referenz in einer linearen Funktion
    -   1 Pixel MMU
    -   basierend auf Daten vom 01.03.-31.10.2018
    -   für Wald (30-100% TCD) / Nichtwald (0-29%) Einteilung 96.4% Overall Accuracy
    -   für Wald (1-100% TCD) / Nichtwald (0%) Einteilung 92.2% Overall Accuracy
    -   (2015: [90%](http://www.gofcgold.wur.nl/documents/CopernicusREDD/12_CopernicusHRlayers.pdf))

-   Dominant Leaf Type (DLT)

    -   aus multitenmporalen Bildern mit Support Vector Mashine (2015) bzw. Random Forest (2018)
    -   1 Pixel MMU
    -   basierend auf Daten vom 01.03.-31.10.2018
    -   96.5% Overall Accuracy

-   Forest Additional Support Layer (FADSL)

    -   um Stadt und Agrarbäume auszuweisen
    -   erstellt aus DLT, TCD, Corine Land Cover 2018 und HRL Imperviousness Degree 2018
    -   1 Pixel MMU

-   Forest Type (FTY)

    -   Wald nach FAO Walddefinition
    -   erstellt aus Verschneidung von TCD und DLT
    -   agrar und urbane Flächen werden mit FADSL maskiert
    -   0.5 ha MMU
    -   10% TCD Grenzwert

-   Small Woody Features

    -   wurden aus VHR Bildern extrahiert und beinhalten Hecken, Alleen, Baumgruppen (TOF)
    -   für 2015 seit März 2020 verfügbar, als 5m Raster oder Vector und aggregierte Version als 100m Raster
    -   2018 ab Ende 2021 verfügbar
    -   mit TCD Waldmaske (\>30% und morphologische Filter) maskiert, trotzdem manche Features doppelt und andere gar nicht kartiert.
    -   Genauigkeit noch nicht validiert, 80% anvisiert (Stand: April 2020)

-   High-Resolution Vegetation Phenology and Productivity product suite ([HR-VPP](https://land.copernicus.eu/pan-european/biophysical-parameters/high-resolution-vegetation-phenology-and-productivity))
    -   10m Auflösung
    -   aus Sentinel-2 Daten
    -   enthält 3 Produktgruppen und 31 Produkttypen pro Jahr
        -   Vegetationsindizes (Leaf Area Index (LAI), Fraction of Absorbed Photosynthetically Active Radiation (FAPAR), Normalized Difference Vegetation Index (NDVI) and Plant Phenology Index (PPI))
        -   Seasonal Trajectories (STs)
        -   Vegetation Phenology Parameters (VPPs)

(*Das Projekt ist aus dem Bedürfnis nach einer aktuellen Waldmaske entstanden. Die Copernicus High Resolution Layers 2018 waren zum Zeitpunkt des Projektbeginns (2020) noch nicht vorhanden!*)

[Landschaftsmodell (Basis-DLM)](https://www.bkg.bund.de/DE/Ueber-das-BKG/Geoinformation/Fernerkundung/Landbedeckungsmodell/Herstellung/herstellung.html)

-   topographischen Objekte der Landschaft und das Relief der Erdoberfläche im Vektorformat
-   aus DGK5, Atualisierungen mit Orthofotos (DOPs)
-   Inhalt orientiert sich an TK25
-   Grundaktualisierung alle paar Jahre (Landestypisch)
-   Spitzenaktualisierung (z.B. Autobahnen) alle paar Monate

[Landbedeckungsmodell (LBM-DE)](https://www.bkg.bund.de/DE/Ueber-das-BKG/Geoinformation/Fernerkundung/Landbedeckungsmodell/Herstellung/herstellung.html)

-   enthält flächenhafte Informationen zur Landbedeckung
-   Das BKG aktualisiert mit Hilfe von Fernerkundungsdaten alle drei Jahre das Digitale Landbedeckungsmodell für Deutschland
-   Aufbauend auf Basis-DLM
-   2012, 2015, 2018
-   Mindestkartierfläche 1 ha und die Mindestkartierbreite 15 Meter
-   bisher wurden hauptsächlich RapidEye-Satellitenbilder genutzt, "zukünftig" Copernicus Sentinel Daten zur Aktualisierung
-   Kombination von Landbedeckung und Landnutzung wird generalisiert für Corine Land Cover genutzt

[Incora Landbedeckung](https://www.mundialis.de/de/deutschland-2019-landbedeckung-auf-basis-von-sentinel-2-daten/)

-   Projekt für ein jährliches Flächenmonitoring
-   durchgeführt von Mundialis
-   Masken für 2016 und 2019 verfügbar
-   Bundesweit
-   auf Basis von Sentinel-2 Daten (10m Auflösung)

[Hansen Tree Cover Map](https://data.globalforestwatch.org/datasets/tree-cover-2000)

-   Landbedeckungskarte für das Jahr 2000
-   Landbedeckungsänderungen 2000
-   2019
-   30m Auflösung generiert aus Landsat
-   Weltweit

## Waldmasken aus Fernerkundungsdaten

[Towards automated Forest Mapping](https://link.springer.com/chapter/10.1007/978-1-4939-7331-6_7)

-   Übersicht zu Methoden und Studien (2017)

### LIDAR

[Waldabgrenzung mithilfe von 3D Fernerkundungsdaten am Beispiel der Walddefinition des Schweizerischen Landesforstinventares](https://ethz.ch/content/dam/ethz/special-interest/usys/ites/ites-dam/Education/Portal%20Forest%20and%20Landscape/Documents/MA_Abstracts_2019/Abstract_SamuelKueng.pdf)

-   Waldmaske 2019 für den Kanton Bern
-   97% Overall Accuracy

### Stereobilder

[Wall-to-Wall Forest Mapping Based on Digital Surface Models from Image-Based Point Clouds and a NFI Forest Definition](https://www.researchgate.net/publication/286453059_Wall-to-Wall_Forest_Mapping_Based_on_Digital_Surface_Models_from_Image-Based_Point_Clouds_and_a_NFI_Forest_Definition)

-   aus Stereo Orthophotos (zusammen mit DTM und DLM)
-   Auflösung 1m
-   für die ganze Schweiz
-   97% Overall Accuracy

### Satellitenbilder (passiv)

[JRC Forest Map](https://earthzine.org/pan-european-forest-maps-derived-from-optical-satellite-imagery)

-   2000, 2006
-   25m Auflösung
-   aus Landsat-7 ETM+ (2000) und IRS-LISS-3, SPOT4/5 Bildern (2006)
-   CORINE Land Cover als Trainingsdaten
-   LUCAS und eForest (Daten der NFIs) Daten zur Validierung
-   k-NN Model (2000) und ANN Model (2006)
-   90.8% Overall Accuracy (2000) und 84% Overall Accuracy (2006)

[Satellitengestutzte Waldflächenkartierung für die Bundeswaldinventur](https://ediss.sub.uni-hamburg.de/volltexte/2007/3172/pdf/070111_oehmichen_dissertation.pdf)

-   für Testgebiete
-   nach BWI-Definitoion
-   aus Quickbird und Landsat (7)
-   zusätzlich mit ATKIS Daten korrigiert
-   referenziert mit BWI-Daten
-   93-97% Genauigkeit

[Tree cover mapping based on Sentinel-2 images demonstrate high thematic accuracy in Europe](https://www.sciencedirect.com/science/article/pii/S0303243419306087)

-   für Testgebiete in Europa
-   unüberwachte k-means Klassifikation von einzelnen Sentinel-2 Szenen
-   Genauigkeit bis 90% (999 Pixel als Referenz)

[Mapping pan-European land cover using Landsat spectral-temporal metrics and the European LUCAS survey](https://www.sciencedirect.com/science/article/abs/pii/S0034425718305546?via%3Dihub)

-   aus Landsat-8 Daten (1 Jahr und 3 Jahre)
-   'used annual and seasonal spectral-temporal metrics and environmental features'
-   MMU 30x30m
-   LUCAS Daten als Referenz
-   12 LULC classes für ganz Europa
-   75.1% Overall Accuracy

[Forest Cover Mapping Based on a Combination of Aerial Images and Sentinel-2 Satellite Data Compared to National Forest Inventory Data](https://doi.org/10.3390/f11121322)

-   aus Sentinel-2 (2017-2019) und Orthofotos (auch DSM)
-   für Baden-Württemberg
-   BWI Daten als Referenzdaten
-   95% Overall Accuracy

### Satellitenbilder (aktiv)

[Forest area derivation from Sentinel-1 data](https://www.isprs-ann-photogramm-remote-sens-spatial-inf-sci.net/III-7/227/2016/isprs-annals-III-7-227-2016.pdf)

-   Waldmaske für Testgebiet in Österreich
-   Sentinel-1A
-   Otsu thresholding and K-means clustering
-   10m Auflösung und 500m² MMU
-   92% Overall Accuracy
-   kann verbeesert werden wenn Stadtgebiete ausgeschlossen werden

[Annual seasonality in Sentinel-1 signal for forest mapping and forest type classification](https://www.tandfonline.com/doi/abs/10.1080/01431161.2018.1479788)

-   für Testgenbiete
-   aus Sentinel-1 Zeitreihen
-   Methodik basiert auf time series similarity measures
-   86-91% Overall Accuracy (forest/non-forest)
-   85% Overall Accuracy (non-forest, coniferous and broadleaf forest)
-   Copernicus HRL als Referenz

[High Resolution Forest Maps from Interferometric TanDEM-X and Multitemporal Sentinel-1 SAR Data](https://link.springer.com/article/10.1007/s41064-017-0040-1)

-   für Testgebiete in Deutschland und Kanada
-   Sentinel-1 und TanDEM-X
-   Random Forest Klassifikation
-   ca 85 - 95% Genauigkeit

[The global forest/non-forest map from TanDEM-X interferometric SAR data](https://www.sciencedirect.com/science/article/pii/S0034425717305795#s0095)

-   globale Waldmaske
-   50m Auflösung
-   aus TanDEM-X Bildern
-   Genauigkeit =\> 90%

## Waldmaske als Nebenprodukt

[Forest Stand Species Mapping Using the Sentinel-2 Time Series](https://www.mdpi.com/2072-4292/11/10/1197/pdf)

-   aus einer Sentinel-2 Szene (Mitte der Vegetationsperiode)
-   mit Random Forest in Wald/Nichtwald klassifiziert
-   99% Overall Accuracy (ausgewählte Polygone als Referenz!)

[Forest Type Identification with Random Forest UsingSentinel-1A, Sentinel-2A, Multi-Temporal Landsat-8and DEM Data](https://www.mdpi.com/2072-4292/10/6/946/pdf)

-   zunächste Segmentierung mit Landsat-8, Sentinel-2 und Sentinel-1 Bildern
-   dann Ableitung von Vegetation durch NDVI-Grenzwert für Segmente
-   dann Wald/Nichtwald Unterscheidung der Vegetation durch Random Forest Klassifizierung von DEM und S-2 Metriken der Segmente
-   Genauigkeit 99%

[Intra-annual reflectance composites from Sentinel-2 and Landsat for national-scale crop and land cover mapping](http://publzalf.ext.zalf.de/publications/a1eb1367-6281-412c-b489-1801d78feddf.pdf)

-   für Deutschland
-   30m Auflösung
-   12 LULC Klassen
-   LUCAS und LPIS Daten als Referenz
-   aus Sentinel-2A und Landsat-8 mutlisensor-Kompositen (10-Tages, Saison- und Jahreskompositen)
-   mit Random Forest Classifier
-   81% Overall Accuracy

## Referenzdaten

[LUCAS](https://ec.europa.eu/eurostat/de/web/lucas/data/primary-data/2018)

-   2018
-   Walddefinition vorhanden
-   georeferenzierte frei verfügbare Referenzdaten
-   genaue Soll- und Ist-Koordinaten sind vorhanden
-   [Beispielstudie](https://www.sciencedirect.com/science/article/pii/S0303243419307317)

[Recent Advances in Forest Observation with Visual Interpretation of Very High-Resolution Imagery](https://link.springer.com/article/10.1007/s10712-019-09533-z)

-   Tools und Methoden zur Nutzung von VHR Bildern als Referenz (Geo-Wiki, LACO-Wiki, Collect Earth)

[VHR_Image_2018](https://spacedata.copernicus.eu/web/cscda/data-offer/core-datasets/-/asset_publisher/SMEFUkzOylMw/content/optical-vhr-multispectral-and-panchromatic-coverage-over-europe-vhr_image_2018-?_101_INSTANCE_SMEFUkzOylMw_redirect=%2Fweb%2Fcscda%2Fdata-offer%2Fcore-datasets)

-   2-4m Auflösung
-   über Copernicus (mit Anmeldung evtl.)

[The Potential of Open Geodata for Automated Large-Scale Land Use and Land Cover Classification](https://www.mdpi.com/2072-4292/11/19/2249/htm)

-   Studie zur Nutzung von Open Data als Referenz zur LULC Klassifizierung
-   anhand von Random Forest Klassifiuierung mit Landsat 7/8 validiert
